import React from 'react';
import OurSolution from '../OurSolution/OurSolution';

const SolutionBlock = () => {
    return (
        <div className='Solution-block' id="future-section">
            <div className='container'>
                <div className='sloution-heading'>
                    <h2>Our Solutions</h2>
                </div>

                <div className='blocks-area'>
                    <OurSolution blockImage="assets/images/digital-image.png" solutionTitle="Digital" solutionHeading="Smart Patient Intake" solutionText="Improving the flow of information between patients and providers can enhance capacity, reduce wait times, and boost the quality of care. Lumed’s adaptive, digital intake enables clinics and hospitals to admit more patients while enhancing the patient experience. Integrated with leading EHRs, Lumed Intake conversationally captures patient details, from insurance data to payment information and consent forms. With just a few clicks, custom options like mental health screening, social determinants, or acuity can be added." moreSolutionText="Lumed Intake also provides patients with transparency and clarity from the outset. They can opt to receive upfront estimates of potential treatment costs, select their preferred language, and set interaction preferences. Built on the pillars of efficiency and personalization, Lumed Intake forms transform the patient admission process like never before.." />
                    <OurSolution blockImage="assets/images/specialized-image.png" solutionTitle="Specialized" solutionHeading="Medical Scribe" solutionText="Envision a healthcare experience where clinicians aren't bogged down by record keeping. Lumed Automatic Speech Recognition (Lumed ASR), precision-tuned for healthcare, ambiently converts conversations into real-time documentation. Whether it's SOAP, POMR, SOURCE, DAR, or CHART format, the software auto-generates documentation that integrates with the chosen structure—or all of them simultaneously." moreSolutionText="With sensitivity to configurable voice commands, Lumed ASR supports dictation-based note-taking and smooth documentation of physical examination results. The scribe is compatible with over 20 languages, recognizes medical acronyms, and can be further refined as necessary. This enables doctors to shift their focus from paperwork to patients, streamlining their workflow, enhancing patient satisfaction, and maintaining meticulously organized records." className="speclized-block" />
                    <OurSolution blockImage="assets/images/interactive-image.png" solutionTitle="Interactive" solutionHeading="MD Copilot" solutionText="With a third of the workforce intending to leave their jobs, and a half reporting burnout caused by work overload, the need for rethinking clinical workflows is greater than ever before. Central to Lumed Copilot is an ensemble of integrated AI tools that craft expert referral letters, propose treatment plans, and accurately assign billing codes. The solution draws from the collective expertise of seasoned medical professionals but adapts to individual preferences and vocabulary the more it is used." moreSolutionText="Lumed Copilot extends beyond mere document assistance. By offering swift, conversational access to comprehensive pharmaceutical databases, physiological analysis, and explanations of benefits, it fosters operational efficiency and clinical excellence concurrently. Equipped with patient data and appointment summaries, the Copilot can also generate highly contextual medical insights, propose alternative treatments, and manage patient follow-ups directly." />
                    <OurSolution blockImage="assets/images/management-img.png" solutionTitle="Comprehensive" solutionHeading="Revenue Cycle Management" solutionText="Imagine a world where the complexities of medical coding, billing, and claims are not only manageable but also effortlessly streamlined. Crafted with precision, clarity, and simplicity in mind, Lumed Billing transforms often daunting billing tasks into smooth, intuitive processes. By keeping pace with regional standards, continuously updated CPT & ICD codes, and evolving CMS guidelines, our system guarantees each bill's transparency and compliance with the Health Billing Act." moreSolutionText="But Lumed Billing is more than just coding and claims management. Utilizing its integrated reasoning engine, the system interprets insurance nuances, payer complexities, and claim denials, automatically suggesting the next steps to optimize costs for both providers and patients. Lumed Billing isn't just about coding and billing—it's a proactive, empowered approach to revenue management. With Lumed, billing evolves from a chore to an asset, always keeping providers a few steps ahead." className="speclized-block" />
                </div>
            </div>
        </div>
    )
}

export default SolutionBlock;